chore: update dependencies, configs, and examples
discordjs/voice-examples pull request #5
Opened 2024-06-21 22:14 UTC by sdanialraza

**Please describe the changes this PR makes and why it should be merged:**
- Updated all the dependencies to their latest version.
- Aligned configs with [discord.js repository](https://github.com/discordjs/discord.js).

To-Do:
- [x] Update base folder
- [x] Update basic folder
- [ ] Update radio bot folder
- [ ] Update recorder folder
- [ ] Update workflow file(s)

2024-06-22 22:07 UTC, vladfrangu requested changes

2024-06-22 22:07 UTC, vladfrangu commented on package.json
>  		"Vlad Frangu <kingdgrizzle@gmail.com>",
```suggestion
		"Vlad Frangu <me@vladfrangu.dev>",
```

2024-06-22 22:07 UTC, vladfrangu commented on package.json
> +	"packageManager": "pnpm@9.1.4",
Can we also get volta pinnings in here? 🙏 you can probably copy it from other repos of mine if need be, but this isn't a blocker

2024-06-22 23:42 UTC, vladfrangu submitted a review, later dismissed

2024-06-22 23:42 UTC, vladfrangu commented on package.json
> +		"node": "18.20",
```suggestion
	"engines": {
		"node": ">=20"
	},
	"packageManager": "pnpm@9.1.4",
	"volta": {
		"node": "20",
```

2024-06-23 00:14 UTC, Jiralite commented on .github/ISSUE_TEMPLATE/01-bug_report.yml
> +      placeholder: Node.js version 18+ is required
```suggestion
      placeholder: Node.js version 20+ is required
```

2024-06-23 01:07 UTC, Jiralite commented on pnpm-workspace.yaml
> +  - 'recorder'
Could we make an examples folder and put them all in here?

2025-01-25 20:01 UTC, merged